### PR TITLE
Add Dragon Dreaming 2022

### PR DESCRIPTION
**Pull request by DoomHammer**

### CODE REVIEW

**Comment by reinhrst** [comment]
I think we want to make the PRs against the event-calendar branch. Then once we're happy with that, we make one large PR from that branch to main. Else we'll have to do some magic to cherry pick these commits from the main back into event-calendar....

**Comment by reinhrst** [comment]
(press "edit" button above and chnage target branch)

**Comment by reinhrst** [comment]
Ah, sorry... I think this has nothing to do with event-calendar right? Which part would you like me to review. Typos in the text? 😛

**Comment by DoomHammer** [comment]
Yup, this one's unrelated. If you have any ideas how to make the images not look shitty, that would be awesome. Otherwise, not much to do here :)

**Comment by reinhrst** [comment]
Add some CSS `article image {max-width: 100%;}` is probably a good start....

I have a shortcode for side-by-side images in my own theme, if you want :)

**Pull request merged**
