### PR TITLE
Support for discord event fields

### PR DESCRIPTION
**Pull request by reinhrst**
We were importing discord events mostly as plain text / markdown, which messed up the layouts and meant that we couldn't use nice displaying. Fixed that on the display side, import side will need fixing.

### CODE REVIEW

**Comment by reinhrst** [comment]
@DoomHammer I made the events look much nicer, however you will have to tweak the import script a bit. Check out the Gejm file for an example.

**Review by DoomHammer — APPROVED** [review]

**Comment by DoomHammer** [comment]
Should we merge this and then update imported events?

**Comment by reinhrst** [comment]
yes :)

**Comment by DoomHammer** [comment]
Pushed directly to main, should look great in a few moments :)

**Pull request merged**
